#!/bin/bash

# PreShrink-VM -- VirtualBox Linux Guest Shrink Preparation Tool (Version 1.0)
# Prepares Linux VirtualBox VM's to be shrunk with the vboxmanage modifyhd
# </path/to/thedisk.vdi> --compact command. (Febuary, 2018)
# By Joe Collins www.ezeelinux.com (GNU/General Public License version 2.0)

# Set functions:

wipe-home() {

echo $'\n'$"Please ignore any pop-up warnings about low disk space."
echo "Wiping free space in /home..."
sudo touch /home/zero
sudo dd if=/dev/zero of=/home/zero status=progress
sudo rm /home/zero
echo "Moving on to /..."

}

wipe-root() {

echo $'\n'$"Please ignore any pop-up warnings about low disk space."
echo "Wiping free space..."
sudo touch /zero
sudo dd if=/dev/zero of=/zero status=progress
sudo rm /zero

}

leave() {

cat << _EOF_

-------------------------
- Preparation complete! -
-------------------------

Shutdown VM and run this command in the host to shrink:
vboxmanage modifyhd </path/to/thedisk.vdi> --compact

_EOF_

exit

}

preshrink-vm-help() {

cat << _EOF_

 PreShrink-VM -- VirtualBox Linux Guest Shrink Preparation Tool

 Preshrink-VM is a tool that prepares Linux VirtualBox VM's to be shrunk with
 the vboxmanage modifyhd </path/to/thedisk.vdi> --compact command. All free
 space must be set to "zeros" for the command to work most efficiently.

 It's a good idea to delete unawnted files, empty the trash and clear caches
 before shrinking your VM.

 Commands:

    preshrink-vm = prepares VM with one active partition:

    preshrink-vm --home = prepares VM with a separate /home partition.

    preshrink-vm --help = shows this help page.

 By Joe Collins www.ezeelinux.com (GNU/General Public License version 2.0)

_EOF_

}

# Execution.

# Check for "--help" option:

if [ "$1" == "--help" ]; then
    preshrink-vm-help
    exit
fi

# Tell 'em who we are...

clear
echo "PreShrink-VM -- VirtualBox Linux Guest Shrink Preparation Tool (Version 1.0)"

# Check for "--home" option:

if [ "$1" == "--home" ]; then
    wipe-home
    wipe-root
    leave
fi

# Check for invalid arguments:

if  [ -n "$1"  ]; then
    echo "PreShrink-VM Error: Invalid argument! Try 'preshrink-vm --help'" >&2
    exit 1
fi

wipe-root
leave
